### PR TITLE
Use ObjectMember interface for Sphinx autoenum members rather than tu…

### PR DESCRIPTION
**Pull request by adamtheturtle**
…ples

Without this, autoenum is broken for Sphinx 7.2.0.

### CODE REVIEW

**Comment by adamtheturtle** [comment]
@domdfcoding If I fix the tests / linting does this look like something you would merge / release?

**Comment by domdfcoding** [comment]
From the failures it looks like ObjectMember doesn't exist in Sphinx 3.2 and 3.3 (added in 3.4 presumably). I'm not sure it's worth the effort to do a special case for those two (old) versions so I will remove them from the CI matrix.

**Comment by domdfcoding** [comment]
I've dropped Sphinx 3.2 and 3.3 from master and rebased

**Comment by adamtheturtle** [comment]
Thank you @domdfcoding . I made a change to satisfy `mypy` and I believe that the 3.12 failures are also happening in `master` and so they are not relevant and should not block the build passing overall.

**Review by domdfcoding — APPROVED** [review]

**Pull request merged**
